// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS0ZFHv_cXqGbe1nWfTfis1c7gw6lTs1Y',
    appId: '1:1061293646399:web:6ea70fb4ed255cb4b34e8a',
    messagingSenderId: '1061293646399',
    projectId: 'teamworkapp-34361',
    authDomain: 'teamworkapp-34361.firebaseapp.com',
    storageBucket: 'teamworkapp-34361.firebasestorage.app',
    measurementId: 'G-ZL81X6L282',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDblkMyye8s5-AGtFuOzGeZvN3xiOo4ZG4',
    appId: '1:1061293646399:android:3619a275de4d7ab2b34e8a',
    messagingSenderId: '1061293646399',
    projectId: 'teamworkapp-34361',
    storageBucket: 'teamworkapp-34361.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8hFg8ekC-YzrQ2nyjJEwRiUHrAj0A-zs',
    appId: '1:1061293646399:ios:e6277dca369b0b16b34e8a',
    messagingSenderId: '1061293646399',
    projectId: 'teamworkapp-34361',
    storageBucket: 'teamworkapp-34361.firebasestorage.app',
    iosBundleId: 'com.example.teamworkapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8hFg8ekC-YzrQ2nyjJEwRiUHrAj0A-zs',
    appId: '1:1061293646399:ios:e6277dca369b0b16b34e8a',
    messagingSenderId: '1061293646399',
    projectId: 'teamworkapp-34361',
    storageBucket: 'teamworkapp-34361.firebasestorage.app',
    iosBundleId: 'com.example.teamworkapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS0ZFHv_cXqGbe1nWfTfis1c7gw6lTs1Y',
    appId: '1:1061293646399:web:82a8002a4cdacdaeb34e8a',
    messagingSenderId: '1061293646399',
    projectId: 'teamworkapp-34361',
    authDomain: 'teamworkapp-34361.firebaseapp.com',
    storageBucket: 'teamworkapp-34361.firebasestorage.app',
    measurementId: 'G-FLPHRBE59N',
  );
}
